### ISSUE TITLE
Darwin Core archive for SIOS

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#22]
Matteo De Stefano will present GBIF and Darwin Core archive data exchange for SIOS in a workshop on [date in April?]

https://sios-svalbard.org/
https://sios-svalbard.org/DMcourses

### SDMS WG Training 4: How to create Darwin Core Archive for biological data 
Date: 2021-04-08 Time: 9:00 - 12:00 (Oslo time) Presenter: Matteo De Stefano, Norwegian Institute for Nature Research <matteo.destefano@nina.no>
* A brief introduction to Darwin Core Archive
* How to work with Darwin Core Archive
* Contributing to GBIF

**Comment by rukayaj** [comment]
Some Q&As:

> What about keywords?
> In the keywords section of metadata in IPT, it is always required a reference Thesaurus/Vocabulary? And keyowrds should be from that, right?
> Are there any most used ones available?
> Any guidelines you can point me about it?

In principle, yes, you would always pick a "keyword" from a vocabulary -- which has a URI (a resolvable identifier).

Yes, ideally the keywords should be from a reference vocabulary, but I think they don't enforce that so you can put whatever you want in there, here https://github.com/gbif/ipt/wiki/GMPHowToGuide#keywordset-general-keywords it says that you can use N/A if you don't have a vocabulary. I don't know of any widely used ones in particular. 

In terms of references I just googled and found this https://eml.ecoinformatics.org/ and this https://eml.ecoinformatics.org/schema/index.html​, but I have never actually looked at them myself.

> I added a new resource in IPT using an existing Archive. No records were available until published, is it correct? Or is it possible to visualize the records even before publishing?
> Also, I tried to set it from private to public before publishing, but it was not visible in the IPT Home, as I expected. Is the publishing step always required? So, what is the meaning of setting it to private after publishing to GBIF?

Yes, you have to publish the resource and for it to be public for records to become available. You can think of it like you have a version of the data which you've published as private, but then in order to get a new version of it public you have to publish it again, with it set to public. Then if you set it to private and publish it again I would imagine it probably hides it again. You can experiment and check. 
 
Also maybe this video is useful https://www.gbif.org/ipt

**Comment by rukayaj** [comment]
Matteo is going to share our contact details during his talk. I guess we can open this issue again if there are any questions etc.
