### ISSUE TITLE
capacity enhancement activities - GBIF community webinar on 28 April

### ISSUE THREAD

**Issue by dagendresen** [gbif-norway/helpdesk#30]
The [GBIF community webinar on 28th April](https://www.gbif.org/event/6hEn5kZGtEJP5ly7qs3Vc1/gbif-community-webinar-april-2021) will focus on capacity development activities at the Secretariat and at the Nodes.

### [GBIF Norway is invited to present our capacity-building activities at the webinar](https://docs.google.com/document/d/1E3IU7OlpnosluP-HykdEk5k950B0omJNTgHRx0dl3G0/edit#).

> Norway
> Topic: Adding all Norwegian GBIF data publishers to Wikidata, or the next phase of the BioDATA biodiversity informatics training program, or possibly about museum specimens as MaterialSample. Our already scheduled BioDATA training course events are currently a bit COV-pending. But we plan to launch a new digital BioDATA training course for Georgia on DNA barcoding data mobilization by June. With Dmitry Schigel and Laura Russell.
> Examples of materials to share: https://www.nhm.uio.no/english/research/projects/biodata/ 

> GBIF Norway intends to make progress on the PID resolver, our citizen science label transcription portal, prototype data annotations based on Wikidata, hosted portal for ecological datasets together with node-partner Living Norway

### Proposed topics
* collaboration with ELIXIR in BioMedData (data management plan training?) -- Rukaya
* recent developments on the new BioDATA course on metabarcoding -- Dag
* recent interaction with Norwegian Oil and Gas -- and follow up from the OpenPSD could also be described as capacity building (?) both for us interacting more with a "new type" of data publisher (private sector) and for building increased capacity with the private sector for publishing data to GBIF -- Vidar?
* recent interaction with the Environment Agency on their interest to publish sampling event-based data with more "fluid" species data concepts (such as Nature in Norway, NiN) -- Dag & Rukaya?
* recent lectures on biodiversity informatics in Trondheim the past months https://www.gbif.no/events/ -- Dag
* the GBIF data access with R course from 2018 for reuse in Tromsø, https://github.com/GBIF-Europe/nordic_oikos_2018_r/blob/master/README.md -- Dag

We could e.g. start shared slides together in Google slides. How do you think?

**Comment by rukayaj** [comment]
Yes let's start some shared slides. Should we do one person presenting everything or have a zoom with all three of us swapping in and out that we just record and submit?

Day one of the BioMedData DMP training just ended. So far it has not been all that relevant for GBIF, but we can certainly mention it. It may be more relevant tomorrow as well. 

Do you think we should also mention how our researchers have become more enthusiastic about using ORCIDs due to BioMedData? Bjørn Petter has done some very impressive work, and I feel like it has definitely been capacity building. But I also think these proposed topics cover everything important and give us more than enough to go on with.

**Comment by dagendresen** [comment]
Swapping between us sounds dynamic and for making an interesting story for the other Nodes :-)
The (emerging) closer collaboration ELIXIR-GBIF might be a more interesting story than the specifics of the DMP...
Interest for ORCID -- you mean Bionomia? not BioMedData? -- yes, cool topic! (however, seems to rather be a topic for the Virtual Nodes meeting in June/July).

**Comment by rukayaj** [comment]
Ok cool! Yes I meant Bionomia!

**Comment by rukayaj** [comment]
I have a google slides file here https://drive.google.com/drive/u/0/folders/1LOzUxnmqibFz1fO_dzWty663CJNoEYSX which we can use, I can start adding some stuff to it today. Is there a template we should use, or shall I just put our logo in the header?

**Comment by dagendresen** [comment]
Super! Thanks! We could use the "new" GBIF slideset template -- or simply add our logo as you mention.

**Comment by rukayaj** [comment]
Is 'Copy of GBIF CiteTheDOI' the new slideset template?

**Comment by dagendresen** [comment]
I hope it follows the template - can try to find the actual template

**Comment by rukayaj** [comment]
I've uploaded a pptx with audio for my slides into the [Webinar recordings folder](https://drive.google.com/drive/u/0/folders/1NUa5uRs-LSk_en6h7CgeeUf0JN_3ttga):
Intro: ~5 secs
BioMedData: ~42 secs
BioData: ~55 secs

**Comment by dagendresen** [comment]
I added the slides with sound clips and video to the GDrive folder as well as to our home page at https://www.gbif.no/events/2021/gbif-community-webinar.html

We can of course update and re-export to mp4 up until close to the webinar starts - if needed.

**Comment by rukayaj** [comment]
Cool, it's nice and short!

**Comment by vidarbakken** [comment]
I worked with the text and recording during the weekend, but I have a technical problem. The external microphone does not work when I try to record. If I try with the internal microphone on the pc the sound is too low. It is strange as this is working in the zoom meetings?? I struggled with this for some hours yesterday, but now I think it will easier if one of you could record the text on the OpenPSD slide. I have written this text:

Norway had the OpenPsd meeting the 5’th of February 2020 in Oslo with 20 attendees. We also had a webcast from the meeting so people from other areas in Norway could join. Since we have had good contact with some of the companies. One result of the meeting was that the company Det Norske Veritas (DNV) published a dataset with almost 2 million records. The data is from a monitoring program taking benthic samples close to oil platforms around the Norwegian coast. Recently we also informed about GBIF in a network meeting where the operating companies on the Norwegian shelf participated.

In addition to the dataset from DNV another six dataset from three private sector have been published

After the meeting we have also searched for smaller companies in Norway involved in biodiversity mapping. We have searched the national database of all private companies. With search keywords like “biodiversity”, “mapping”, “nature” etc. we have identified another 26 potential companies. We will soon start to contact these companies and perhaps organize a web meeting.

**Comment by rukayaj** [comment]
Ok no problem Vidar, I will record it. Sorry to hear you had to spend so much time struggling with it!

**Comment by vidarbakken** [comment]
Good, thanks!

**Comment by rukayaj** [comment]
I notice Dag already did it! Thank you @dagendresen :)

**Comment by rukayaj** [comment]
Well done team!
