### ISSUE TITLE
AgentActions paper 

### ISSUE THREAD

**Issue by rukayaj** [gbif-norway/helpdesk#36]
David has asked for feedback on a paper for the AgentActions extension: 
https://docs.google.com/document/d/1VoqpGfyN_8FOILlrY8lZOZB3pZDol0S6-mom_kHGEHU/edit?ts=609d2bff#heading=h.eugmjzvvj9fv

**Comment by dagendresen** [comment]
Some questions to maybe address in the Agent action abstract?

### MUSIT person module database structure
Did MUSIT add separate fields for ORCID and QID, or do we keep these in the same field? Is this field repeatable one-to-many so that we can record more than one person-identifier for each person?

### MUSIT curator/edit interface
Does the MUSIT CMS interface allow adding these identifiers now, or do you need to add them in direct contact with Stein and/or Svein?

### Are **name strings** normalized
Does the person module in MUSIT in any way maybe include ALL person name strings (aliases) in a normalized relation linked to the person entries? Does the MUSIT person module record name aliases? Only linked from an identified person or including also all (?) name-strings also for people not yet identified? E.g. Can a name-string entity be "moved" to another person (re-linked to another person entry) - or must the "name-string" then be copied (manually?) to another person?

### Coverage of people with/without ORCID ID or QID?
Can we make some metrics for how many collectors and identifiers now have ORCID IDs or QIDs? Maybe also how many _name-strings_ are linked to an identified person? (with/without PID?).

**Comment by dagendresen** [comment]
See also https://github.com/tdwg/attribution/issues

**Comment by dagendresen** [comment]
Bjørn Petter:

> Ja kort fortalt er det gjort slik:
> 
> `<personID>WIKIDATAID</personID>` er lagt inn i databasenes personmoduler post for post eller importert. Personmodulen knytter sammen synonyme navn, slik at wikidataID legges inn kun en gang per person per samling.
> 
> I tillegg har vi laget wikidataposter for bidragsytere til samlingene. Vi har brukt kilder/bøker som er skannet hos Nasjonalbiblioteket og sentrale verk har f.eks. vært "Norske skulefolk", "Norges apotekere og farmasøyter" og "Norges leger" som alle er utgitt i 2/mange utgaver. Disse sammen med Digitalarkivet har vært sentrale kilder for å skape wikidatapostene med referanser.
> 
> Frictionless data-fila `"problems_collector_date"` har senere vært grunnlag for å forbedre/rette enten: 1. Dato, 2. Samler/bestemmer, 3. Wikidataposten hvor f.eks. dødsdato mangler. Noen ganger har vi også lagt inn feil wikidataID i personmodulen. F.eks. i karplantesamlingen har frictionless data vært grunnlag for å rette ca. 1500 poster så langt.

**Comment by rukayaj** [comment]
I have added a bit to the document, I think I have covered all of your questions except "Coverage of people with/without ORCID ID or QID?". I would have thought bionomia has an interface for seeing this? I will take a look tomorrow anyway.

**Comment by rukayaj** [comment]
I don't think there are any outstanding tasks left for this, unless someone wants to follow up with David and ask what became of the paper?
